### ISSUE TITLE
Invalid `RNReanimated.podspec` file: different prefix: "" and "/Users/khanhnguyen/Documents/React Native Code/Hero/ios/Pods".

### ISSUE THREAD

**Issue by emonno13** [obytes/react-native-template-obytes#139]
# Summary:

I got some errors with the guide:
https://starter.obytes.com/docs/getting-started/create-new-app

Mac Pro 14 M1 Pro 2021
Xcode 14 
Ios 16.2
node 18.14.2
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]

## Steps to reproduce:

```
npx create-obytes-app@latest Hero

yarn ios

```
## Additional notes:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/53046415/223175048-a5f5c4ca-a3c9-4038-a8d0-703ab0e6240f.png">

#### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by yjose** [comment]
Hey @emonno13, look like the issue is related to pod installation, can you  please make sure to run `yarn prebuild --clean`   to regenerate iOS and android folders. this probably will fix your issue. 
Any way we just update the project to the last expo sdk, so you can try again and let us know if the issue still persist
