### ISSUE TITLE
Android APK size is huge compared to ipa.

### ISSUE THREAD

**Issue by ejkkan** [obytes/react-native-template-obytes#223]
# Summary:
Building the exact same application, with not much addons from the template itself, the app builds sizes are extremely different.

ipa: 10,3mb.
apk: 49,5mb.

Do i have to manually add things like "enableProguardInReleaseBuilds" to minify the android build or are there other measure that I can take to reduce the android apk?

**Comment by yjose** [comment]
Hey @ejkkan, I think it's normal as an APK is supposed to have multiple architecture builds in the same file. And for Google Play, you should generate AAB instead of APK. Check out this link for more information: [APK vs AAB: Which is Better for Android?](https://www.geeksforgeeks.org/apk-vs-aab-which-is-better-for-android/)

If you are building your app with EAS, we are configuring the build to [generate AAB for the production build.](https://github.com/obytes/react-native-template-obytes/blob/20509988b333421204d319ce9d37952767cf106e/eas.json#L13)

Of course, there are some tricks to reduce APK size, but I think generating [AAB format instead of APK is the right choice.](https://www.4waytechnologies.com/blog/how-to-reduce-apk-size-in-react-native-expo#:~:text=2.-,Consideration%20of%20the%20Play%20Store%20data,-This%20method%20may)

**Comment by ejkkan** [comment]
Amazing. Had not tried a production build yet so did not notice this. 

Thanks for the detailed answer.
