### ISSUE TITLE
How to handle ENV variables for CI?

### ISSUE THREAD

**Issue by BlvckParrot** [obytes/react-native-template-obytes#336]
How do you handle ENV variables for CI runs, without having any .env file in remote repository?

**Comment by yjose** [comment]
You just need to add them as global environment variables in your repository, and the script should read them from the system. please try it and let me know in case it's not working as expected

**Comment by heyanurag** [comment]
@yjose 

I just read this guide - [https://starter.obytes.com/ci-cd/app-releasing-process/](https://starter.obytes.com/ci-cd/app-releasing-process/)

It says for a QA release I have to run `prebuild:staging` and then `build:staging:__` commands. (Similar flow for production).

It further says:

> The above commands will generate the required credentials for the build and store them in EAS servers so that we can use them later to trigger the build from GitHub actions.

Does this mean that for every QA/production release I have to run the build locally -- So that the env variables for a particular environment are updated on the eas servers? How does eas handle env variables for different environments. I am a little confused with the release flow.

Thank you for this amazing starter! Its a life saver 💟

**Comment by SamuelLHuber** [comment]
is it intended that ```npx create-obytes-app@latest MyApp``` does not include the .env files in the .gitignore ? I'd assume for security reasons to not check secrets into the repo it would be best practice to include any .env in the .gitignore

Is this handeled by the precommit hooks?

**Comment by yjose** [comment]
@SamuelLHuber @heyanurag, just added an new section in the docs for more clarity regarding env files and github action 
https://starter.obytes.com/ci-cd/app-releasing-process/#github-action-and-env-variables

**Comment by joshuadiezmo** [comment]
> [@SamuelLHuber](https://github.com/SamuelLHuber) [@heyanurag](https://github.com/heyanurag), just added an new section in the docs for more clarity regarding env files and github action https://starter.obytes.com/ci-cd/app-releasing-process/#github-action-and-env-variables

The current approach requires manually adding specific configurations to every workflow (e.g., eas build, expo-doctor, lint-ts, test), which is inefficient and prone to errors.

Can you recommend a more efficient way to manage these configurations across all workflows?
