### ISSUE TITLE
ESlint auto fix on save is not work in react-native-template-obytes v7.0.2

### ISSUE THREAD

**Issue by yearsalary** [obytes/react-native-template-obytes#410]
# Summary:
ESlint auto fix on save is not work in react-native-template-obytes v7.0.2

## Steps to reproduce:
1. ESlint and Prettier install
2. npx create-obytes-app@latest MyApp
3. pnpm install 
4. Intentionally remove line breaks in JSX or TS code
5. Even after saving, new line breaks do not appear.

## Expected behavior:
ESlint auto fix on save is work in react-native-template-obytes

## Additional notes:
my solution is that to Add agin @react-native-community/eslint-config in devDependencies and 
add @react-native-community in .eslintrc.js extends.
it is work for me.

**Comment by yjose** [comment]
Hey @yearsalary, thank you for reporting this. I am using the latest version, and the auto-fix feature seems to be working as expected for me. 

I'm not sure what you mean by line breaks in your test. The best way to test it is to import something that you are not using and see if the autosave removes it or not.

Sometimes, the issue with VS Code is related to other installed extensions.
Your solution of installing the React Native Community ESLint config shouldn't be the answer, as we removed it in favor of the Expo config.

The first step is to test running `pnpm lint --fix`. If it works and autosave is not working, then the issue is related to VS Code, not the project itself. If `pnpm lint --fix` does not work either, then there is a problem with the ESLint configuration.

**Comment by yearsalary** [comment]
Hello @yjose Thank you for your comment. I already tested the things you mentioned above. The test results indicated that the ESLint configuration is incorrect because the `pnpm lint --fix` command is not working.

I think I found the reason in the EXP docs (https://docs.expo.dev/guides/using-eslint/#setup-1)
Following the documentation, I added the plugin and rule to .eslintrc.js, as shown in the image below, so that the issue can be fixed.

![스크린샷 2024-12-18 오전 11 06 05](https://github.com/user-attachments/assets/775f64b5-c7ff-46d8-997d-afb7c9568dc4)

Afterward, some original template components (like the progress bar) and utility code were auto-fixed by Prettier.
![스크린샷 2024-12-18 오전 11 07 16](https://github.com/user-attachments/assets/0f90d324-0d3b-4d12-9983-b5f911238bce)

**Comment by yjose** [comment]
Thank you for reporting this. It looks like we need to add Prettier explicitly in the plugin to make it work correctly.
